{{--
    Body of the placeholder attachment written by `cicto:seed-storage`.

    Carries its own inline styling for the same reason the report views do:
    dompdf parses a small, old subset of CSS and silently drops the rest, so a
    class from the application stylesheet renders as unstyled text.

    Every field on the page comes from the document row it is attached to. That
    is deliberate -- a tester who opens two of these has to be able to tell them
    apart, and a placeholder that reads identically for all nine proves nothing
    about whether the right file came back off the disk.
--}}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8">
    <title>{{ $document->control_number }}</title>
</head>
{{--
    Helvetica rather than DejaVu Sans, and the difference is 100x on disk.
    DejaVu is not one of the fourteen PDF core fonts, so dompdf embeds the whole
    face in every file it writes -- 879KB per placeholder, against 8KB when the
    reader is left to supply the font. Multiplied by a register of documents on
    metered object storage that is real money for a page of six table rows.
    Latin-1 covers everything on it.
--}}
<body style="font-family: Helvetica, Arial, sans-serif; font-size: 12px; color: #111827;">

    <div style="border-bottom: 2px solid #111827; padding-bottom: 8px; margin-bottom: 18px;">
        <div style="font-size: 18px; font-weight: bold;">{{ $office }}</div>
        <div style="font-size: 11px; color: #6b7280;">Document Tracking System &mdash; sample attachment</div>
    </div>

    <p style="background: #fef3c7; border: 1px solid #f59e0b; padding: 8px; margin-bottom: 18px;">
        <strong>This is not a real document.</strong> It was generated by
        <code>cicto:seed-storage</code> so that testers have something to open,
        download and sign. It carries no official effect.
    </p>

    <table style="width: 100%; border-collapse: collapse;">
        <tr>
            <td style="border: 1px solid #d1d5db; padding: 6px; background: #f9fafb; width: 34%;"><strong>Control number</strong></td>
            <td style="border: 1px solid #d1d5db; padding: 6px;">{{ $document->control_number }}</td>
        </tr>
        <tr>
            <td style="border: 1px solid #d1d5db; padding: 6px; background: #f9fafb;"><strong>Title</strong></td>
            <td style="border: 1px solid #d1d5db; padding: 6px;">{{ $document->title }}</td>
        </tr>
        <tr>
            <td style="border: 1px solid #d1d5db; padding: 6px; background: #f9fafb;"><strong>Originating office</strong></td>
            <td style="border: 1px solid #d1d5db; padding: 6px;">{{ $office }}</td>
        </tr>
        <tr>
            <td style="border: 1px solid #d1d5db; padding: 6px; background: #f9fafb;"><strong>Document type</strong></td>
            <td style="border: 1px solid #d1d5db; padding: 6px;">{{ $type }}</td>
        </tr>
        <tr>
            <td style="border: 1px solid #d1d5db; padding: 6px; background: #f9fafb;"><strong>Priority</strong></td>
            <td style="border: 1px solid #d1d5db; padding: 6px;">{{ $priority }}</td>
        </tr>
        <tr>
            <td style="border: 1px solid #d1d5db; padding: 6px; background: #f9fafb;"><strong>Generated</strong></td>
            <td style="border: 1px solid #d1d5db; padding: 6px;">{{ $generatedAt }}</td>
        </tr>
    </table>

    @if ($document->description)
        <p style="margin-top: 18px;"><strong>Description</strong><br>{{ $document->description }}</p>
    @endif

</body>
</html>
